on:
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    # only version here so that only one zip is created
    strategy:
      matrix:
        os: [ubuntu-22.04]
        racket-variant: ['CS']
        racket-version: ['8.14']
    name: Test on Racket ${{ matrix.racket-variant }} ${{ matrix.racket-version }} on ${{ matrix.os }}	
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nasm
      run: sudo apt-get install nasm
    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - name: Version info
      run: |
        nasm --version
        gcc --version
    - name: Install assignments package
      run: |
        raco pkg install --auto ../assignments/
    - name: Run tests
      run: |
        raco test knock-plus/test/interp.rkt # all should pass
        raco test knock-plus/test/compile.rkt 2>&1 | grep 'failures' # should not pass
    - name: Zip
      run: |
        zip knock-plus.zip `git ls-files knock-plus`
    - name: Archive knock-plus
      uses: actions/upload-pages-artifact@v3
      with:
        name: knock-plus
        path: knock-plus.zip
