on: [push, workflow_dispatch]

jobs:
  build-and-test:
    # only version here so that only one zip is created
    strategy:
      matrix:
        os: [ubuntu-22.04]
        racket-variant: ['CS']
        racket-version: ['9.0']
    runs-on: ${{ matrix.os }}
    name: Test on Racket ${{ matrix.racket-variant }} ${{ matrix.racket-version }} on ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}

    - name: Install clang
      run: |
        sudo apt install -y clang libssl-dev

    - name: Version info
      run: |
        clang --version
        gcc --version

    - name: Install assignments package
      run: |
        raco pkg install --auto ../assignments/

    - name: Run tests
      run: |
        raco test -p assignments
        raco test knock-plus/test/compile.rkt 2>&1 | grep 'failures' # should not pass
        #
    - name: Create zips
      run: |
        mkdir zips/
        zip zips/knock-plus.zip `git ls-files knock-plus`

    - name: Archive zips
      uses: actions/upload-artifact@v4
      with:
        name: zips
        path: zips
